# Generated by Django 6.0.5 on 2026-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("spotify_uri", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                ("duration_ms", models.IntegerField()),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
    ]
