# Generated by Django 6.0.5 on 2026-08-16 09:37

from django.db import migrations, models

import authentication.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(
                default=authentication.models.generate_six_digit_token, max_length=6, unique=True
            ),
        ),
    ]
