# Generated by Django 6.0.5 on 2026-08-19 15:49

from django.db import migrations, models

import authentication.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_emailverificationtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(
                default=authentication.models.generate_verification_token,
                max_length=64,
                unique=True,
            ),
        ),
    ]
